[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "teleparty-lakehouse"
version = "0.1.0"
description = "IMDb Lakehouse to OLAP Pipeline for Teleparty-Lakehouse"
authors = [
    {name = "Applicant", email = "applicant@example.com"}
]
dependencies = [
    "pyspark>=3.5.0",
    "duckdb>=1.0.0",
    "kagglehub"
]
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]
